[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "6cc63132398edaec1631f88dedfd3395537a2e6d"
os = "macos"

    [[GnuPG.download]]
    sha256 = "dd612f1228bc14a43c66006861d0dc3236ed1b8b00d7dcb2406ecf3b4308656a"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.aarch64-apple-darwin.tar.gz"
[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "c54a7788878a1d586ae44ffc331ee8baa5be8855"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "8041215b99ca7bd019456677ddc51755531dc160906b146109c9dbc2d894d1ae"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.aarch64-linux-gnu.tar.gz"
[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "8aa4443e7275dc643b6ede3e4a6153b5a6517b7f"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "c655056dcad23195687066c3c66f421f8fec986202c21b58c7fe06e20b85c2a1"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.aarch64-linux-musl.tar.gz"
[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "38258a457da5d527c174fdf08a5465d0255b179b"
os = "freebsd"

    [[GnuPG.download]]
    sha256 = "3830c8321de15755207a79151de02afdaad7f4452dba52813bd9dafa7e7a0e2f"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.aarch64-unknown-freebsd.tar.gz"
[[GnuPG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b4d910a1117aad8cc5a4f8d400758f8e67d86d3b"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "de6664d383a1d0ab92ea44b7f04b501e57b9a2ea827a5590fe17a94ff336519a"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.armv6l-linux-gnueabihf.tar.gz"
[[GnuPG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d38b9f572a93a7f8ed8441b2f016704ff8b5739"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "c36fcc8d46d8e2b1a0a1d52e6f21e67c1bed4daefcc2c1381cbd5e75d6580517"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.armv6l-linux-musleabihf.tar.gz"
[[GnuPG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b5a876aeb33900e79ac895469944651de4710030"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "019be6c19c095d90a408f71fa823b19b47c8f6dc04795561ff0e271b60c5d600"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.armv7l-linux-gnueabihf.tar.gz"
[[GnuPG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "01d6aad5d554f581b3241e27429222456f22e86c"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "51691f74a722b5207984fefb037697eecfb79e1a747bbe4ec203b73feed5072c"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.armv7l-linux-musleabihf.tar.gz"
[[GnuPG]]
arch = "i686"
git-tree-sha1 = "10d60bce5f4ddeba08b32f0682bbc8842b2de75e"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "12ad1545824ac49ae0b57ba21fef2a2e5aff345457379168b676b8e122c890c9"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.i686-linux-gnu.tar.gz"
[[GnuPG]]
arch = "i686"
git-tree-sha1 = "0766d391932534eae93f1c575c3456ccc2bb08a0"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "d0d31d9995fd9cfcbe66879b28f6863c29774d81fe118adb928105b3fdb76e61"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.i686-linux-musl.tar.gz"
[[GnuPG]]
arch = "i686"
git-tree-sha1 = "835916af2d330103d3991b2e0440b1f8fa5b47cc"
os = "windows"

    [[GnuPG.download]]
    sha256 = "b4aa4b43be40d4c7523fed0d01bac8698a7f8a5d6a3215d8adf92965463ae12e"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.i686-w64-mingw32.tar.gz"
[[GnuPG]]
arch = "powerpc64le"
git-tree-sha1 = "be4b7a90fbcb8ba8d1c523d89a7df04bf2ea9c68"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "d88161ec448cbb8f6969fad51de47e3bba06eb57f8f02ede681cb4a09a761cb0"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.powerpc64le-linux-gnu.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "3bddc1208c8035149e208622a9e80152f7beafd2"
os = "macos"

    [[GnuPG.download]]
    sha256 = "a2cd6deba2ec27ec24291866fa59d2d6479204d463daef7588f75c3ba422c11d"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.x86_64-apple-darwin.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "9a711c4aa728432076bbc257304aeee38f83be59"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "86f462ef43217347b5f381f718bcd1c129551f7e78d52b4019c1b86a8f682f9d"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.x86_64-linux-gnu.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "79e7424b0e6be984239b9bdf4e3d7e0620a56f1c"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "1ba18f0fe5ca47d247fc9b7711c84fcffa9c7ca88d7376cdae39bf533105bade"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.x86_64-linux-musl.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "b629d63b270a673bcfb57b72221d16f7538f357c"
os = "freebsd"

    [[GnuPG.download]]
    sha256 = "06067c78306698eb69ba540daa0b30eb72dbd8d597ff643a570f1d0a9e1ce3ee"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.x86_64-unknown-freebsd.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "3a223101b8888220a03780ca720db562b88caf06"
os = "windows"

    [[GnuPG.download]]
    sha256 = "1b48b2278b574c2182aeb825c58e5a5dcafaeacfe536292738b8abef7d037381"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.4.8+0/GnuPG.v2.4.8.x86_64-w64-mingw32.tar.gz"
