[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "8a173bbb5795655cf8709e6b5b4566c72041c1a4"
os = "macos"

    [[GnuPG.download]]
    sha256 = "6d3a4d6025f0fc830081e7053ac3b7fc396d5f56b7bca20792620f44b1d5123e"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.aarch64-apple-darwin.tar.gz"
[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "33e507fe8edc86508d2237da2091e0b0cb4d5875"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "14cb2f6e93b774527b1402979aaea2408bfcd81f53e23751ad4d29f36bced2cf"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.aarch64-linux-gnu.tar.gz"
[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "9625daf1a72f6e601541bced66afb0dee00c6c31"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "d34dc60145d6e4a36b258f59ed0fa43bc86e11d200653c0302760ea3b73baeca"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.aarch64-linux-musl.tar.gz"
[[GnuPG]]
arch = "aarch64"
git-tree-sha1 = "e46a69ba6785e0bf6f5424df01f99173cb9c1e46"
os = "freebsd"

    [[GnuPG.download]]
    sha256 = "2ea231d6f435437fbb40997215ee778e6966eb7515203f8c192a9dbdd1d9cf09"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.aarch64-unknown-freebsd.tar.gz"
[[GnuPG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9ebd29fefdbd6cf8634c98471d3955c15db28e48"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "22173d0125bab9276bbd683e1529580de9baf053b3179386a6f9efd4469cec6b"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.armv6l-linux-gnueabihf.tar.gz"
[[GnuPG]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d18878b3c92f9a43523031db1593aadeb2f3b981"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "cb84838f5e45f6b501706d2ec1b50735a48f80a7cbdcbddc316454bf0005d5a0"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.armv6l-linux-musleabihf.tar.gz"
[[GnuPG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a66c655c084eda00767102779bb9f9b638274fc7"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "18eb696b24e2b102e39755d2464146ebb924a6f03d8cf16293e656082dcaf00c"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.armv7l-linux-gnueabihf.tar.gz"
[[GnuPG]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ffc1e2f3e5832b9a8d6c09e7ebaf1963fde7dd0"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "57bb31aafe8c340ee801a0919cd1c91a6986b6d1125c8f126f4d80e7ddc2e574"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.armv7l-linux-musleabihf.tar.gz"
[[GnuPG]]
arch = "i686"
git-tree-sha1 = "98d65b200cf0c6decef469558486357410e282a5"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "5d499e11a19b9f12e443d44c81f4eeac0e2ba73c1db17c20aaf0de4eef793bb9"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.i686-linux-gnu.tar.gz"
[[GnuPG]]
arch = "i686"
git-tree-sha1 = "293bd6580a0f174c4c27b542e6a1861c39285218"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "01c968c7f67648747d0592b548b899ee62ebadd651b01c78a6389bac22f2f1cc"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.i686-linux-musl.tar.gz"
[[GnuPG]]
arch = "i686"
git-tree-sha1 = "9ddaca91bd2e466a992d106a2f4fba515fb5e19f"
os = "windows"

    [[GnuPG.download]]
    sha256 = "52616d5ea635cab1280166658c71c01553dcbe7643cf435deff57d6a15144811"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.i686-w64-mingw32.tar.gz"
[[GnuPG]]
arch = "powerpc64le"
git-tree-sha1 = "1151ccd8cfc8c008a6494b897582eab1285081dd"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "151de6cd1257dfa2d58a1c89d9fe14d494eb16af84b792b4f2cfdcf85c56ecba"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.powerpc64le-linux-gnu.tar.gz"
[[GnuPG]]
arch = "riscv64"
git-tree-sha1 = "e8b7a96720b700c3aa4e39753b2241b4d5087307"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "ff640f93f62f368152d32c3d3c26a7a277693e1ea0f801dc6703bea214d58bca"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.riscv64-linux-gnu.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "7e2deee5dc238a58091dbcc587ab9456c30bb1eb"
os = "macos"

    [[GnuPG.download]]
    sha256 = "d900d16acc1266b445ba4ace83bc631dbacb5c53eb3ee896c7185b4f8ee068ee"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.x86_64-apple-darwin.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "2b02a37ed3045fb83c3175e3ca65d092737189fb"
libc = "glibc"
os = "linux"

    [[GnuPG.download]]
    sha256 = "052ec3a8cca819771392b3bb1c89b312e4d0179c47e96e29282029c167e38e79"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.x86_64-linux-gnu.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "5cf3316f1b7c43a9d9d9d8027d95490cb20d528a"
libc = "musl"
os = "linux"

    [[GnuPG.download]]
    sha256 = "06c3e94ed1e3366f425311d4553a659b9f0fbe6e55d034a4141a039d94b7b563"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.x86_64-linux-musl.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "b24b678cea8c2b5833589999064f5a8bd32aec0b"
os = "freebsd"

    [[GnuPG.download]]
    sha256 = "300cb8c086a6ebb2432dcb32574ae4379bff29350f6f3e272047433385c166a6"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.x86_64-unknown-freebsd.tar.gz"
[[GnuPG]]
arch = "x86_64"
git-tree-sha1 = "796d47f1d262d562c65054c4ae9ce556e58434be"
os = "windows"

    [[GnuPG.download]]
    sha256 = "75f4bc587b73fc983f1382a2216a7ef2262042aef1d2a419d699d73c50a143a8"
    url = "https://github.com/JuliaBinaryWrappers/GnuPG_jll.jl/releases/download/GnuPG-v2.5.16+0/GnuPG.v2.5.16.x86_64-w64-mingw32.tar.gz"
